### ISSUE TITLE
Undeletable, unlistable flowfiles stuck in queue between ExtensionCallMarkLogic and DeleteMarkLogic

### ISSUE THREAD

**Issue by julianwang90** [marklogic/nifi#76] opened 2019-10-03 14:50 UTC
In a typical flow consisting of the following:
1. Use PutMarkLogic to load documents onto STAGING database through a DHF input flow
2. Use ExtensionCallMarkLogic to run DHF harmonisation flow and load documents onto FINAL database
3. Use DeleteMarkLogic to remove all documents from STAGING following successful harmonisation

Frequently, flowfiles will end up in the queue between the ExtensionCallMarkLogic and DeleteMarkLogic processors. These flowfiles, whilst shown on the NiFi UI, are not present when trying to list them. Attempts to clear the queue also result in an error saying there are no items to clear (despite the UI showing there are items in the queue, see screenshots below).

This behaviour only seems to occur in the queue upstream of the DeleteMarkLogic processor. The workaround solution has been to restart the NiFi service, after which either the UI will show no items in the queue, or, the previously unviewable, unclearable items will be able to be cleared.

Using MarkLogic 1.8.0.3 NiFi processors.

**Comment by rjrudin** [comment] 2021-01-22 20:57
I believe this is a duplicate of #91 . I verified that the original flowfile sent to DeleteMarkLogic would get "stuck" . This was due to a commit() call on the session before a destination relationship had been set on the original flowfile. 

I am closing this in anticipation of 1.9.1.5 fixing it.

**Closed by rjrudin** 2021-01-22 20:57 UTC
